services:
  - type: web
    name: flask-app
    env: python
    runtime:
      builder: paketo-buildpacks/python
    buildCommand: pip install --no-cache-dir -r ./requirements.txt && python app.py
    startCommand: gunicorn --worker-class gevent --workers 3 app:app
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
